{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "orchestrator.roleBindingName" . }}
  namespace: {{ index .Values.workflows.controller.workflowNamespaces 0 }}
rules:
  - apiGroups: [ "argoproj.io" ]
    resources:
      - "customresourcedefinitions"
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "orchestrator.roleBindingName" . }}
  namespace: {{ index .Values.workflows.controller.workflowNamespaces 0 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ index .Values.workflows.controller.workflowNamespaces 0 }}
roleRef:
  kind: Role
  name: {{ include "orchestrator.roleBindingName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}