workflows:
  enabled: true

  singleNamespace: true

  executor:
    securityContext: &securityContext
      runAsNonRoot: true
      runAsUser: 8737

  controller:
    workflowNamespaces:
      - argo

    workflowDefaults:
      archiveLogs: true
      serviceAccountName: ""

    podSecurityContext: *securityContext

    serviceAccount: &sa
      create: true
      name: ""

  workflow:
    rbac:
      create: true
    serviceAccount:
      create: true
      name: workflow
      annotations: {}

  mainContainer:
    securityContext: *securityContext

  server:
    extraArgs: [ --auth-mode=server ]
    podSecurityContext: *securityContext
    serviceType: "ClusterIP"
    loadBalancerIP: ""
    serviceAccount: *sa

  artifactRepository:
    archiveLogs: true
    gcs:
      keyFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
    s3: {}
    useDefaultArtifactRepo: false