rbac:
  create: true
  name: &name "argo"

workflows:
  enabled: true

  singleNamespace: true

  executor:
    securityContext: &securityContext
      runAsNonRoot: true
      runAsUser: 8737

  controller:
    workflowNamespaces:
      - *name

    workflowDefaults:
      archiveLogs: true
      serviceAccountName: *name

    podSecurityContext: *securityContext

  workflow:
    rbac:
      create: true
    serviceAccount:
      create: true
      name: workflow
      annotations: {}

  mainContainer:
    securityContext: *securityContext

  server:
    extraArgs: [ --auth-mode=server ]
    podSecurityContext: *securityContext
    serviceType: "ClusterIP"
    loadBalancerIP: ""

  artifactRepository:
    archiveLogs: true
    gcs:
      keyFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
    s3: {}
    useDefaultArtifactRepo: false